FLOW-969 : f-countdown component
cldcvr/flow-core pull request #208
Opened 2023-12-11 07:05 UTC by mayankfulera

### Checklist for raising a PR

- [ ] Gone through UX documnetation for adding new features.
- [ ] All necessary unit tests covered.
- [ ] Required comments added for generating component manifest file? you can find details [here](https://custom-elements-manifest.open-wc.org/analyzer/getting-started/)
- [ ] Did you check the contributing doc?
- [ ] Did you check the existing issues for similar queries?

### Describe your PR
- `f-countdown`: component added in flow-core

<img width="1365" alt="Screenshot 2023-12-11 at 12 35 11 PM" src="https://github.com/cldcvr/flow-core/assets/23555670/0c7d7cf6-c57b-4ab0-a687-3aeaa4e4a253">

### Add additional question here

- [ ] `Yes`
- [ ] `No`
- [ ] `NA`

2023-12-11 13:09 UTC, vikas-cldcvr requested changes

2023-12-11 13:09 UTC, vikas-cldcvr commented on packages/flow-core/src/components/f-countdown/f-countdown.ts
> +	get secondsDuration() {
Can we add more validations here, So we accept a number here which is greater than 0 and the upper limit needs to be 3600

if the string is specified then it must through an error for an invalid format

2023-12-11 13:09 UTC, vikas-cldcvr commented on packages/flow-core/src/components/f-countdown/f-countdown.scss
> +	.mask {
same here `f-countdown-mask`

2023-12-12 07:19 UTC, mayankfulera commented on packages/flow-core/src/components/f-countdown/f-countdown.ts
> +	fill = "";
this.fill is referenced with many conditions, to check whether we have custom color or not, if this.fill always have a value, this.state won't work at all.

2023-12-18 12:44 UTC, vikas-cldcvr approved these changes

2023-12-18 12:44 UTC, merged