FLOW-1036 | f-button packed category addition
cldcvr/flow-core pull request #213
Opened 2023-12-19 09:31 UTC by mayankfulera

### Checklist for raising a PR

- [ ] Gone through UX documnetation for adding new features.
- [ ] All necessary unit tests covered.
- [ ] Required comments added for generating component manifest file? you can find details [here](https://custom-elements-manifest.open-wc.org/analyzer/getting-started/)
- [ ] Did you check the contributing doc?
- [ ] Did you check the existing issues for similar queries?

### Describe your PR
- `f-button` `packed` category addition

### Add additional question here

- [ ] `Yes`
- [ ] `No`
- [ ] `NA`

2023-12-19 13:24 UTC, vikas-cldcvr requested changes

2023-12-19 13:24 UTC, vikas-cldcvr commented on packages/flow-core/src/components/f-button/f-button.scss
> +			&[state="#{$state}"][category="packed"] {
you can do to avoid code duplication
&[state="#{$state}"][category="transparent"],&[state="#{$state}"][category="packed"]

2023-12-19 13:24 UTC, vikas-cldcvr commented on packages/flow-core/src/components/f-button/f-button.scss
> +					height: 0%;
`height:fit-content` will it work here?

2023-12-20 04:35 UTC, mayankfulera commented on packages/flow-core/src/components/f-button/f-button.scss
> +					height: 0%;
it works, even removing the height

2023-12-20 07:03 UTC, vikas-cldcvr approved these changes

2023-12-20 07:03 UTC, merged